"""
One-time migration script — mypka.db → Cloudflare D1 (larry-db).

Reads notes / journal / people from the local SQLite file and prints
INSERT statements that can be piped into:

    wrangler d1 execute larry-db --remote --file migration.sql

Run with:
    python migrate-to-d1.py > migration.sql

The script never deletes anything in mypka.db — it only reads.
"""

import sqlite3
import sys
from pathlib import Path

# ─── paths ─────────────────────────────────────────────────────
HERE = Path(__file__).parent
LOCAL_DB = HERE / "mypka.db"

if not LOCAL_DB.exists():
    sys.stderr.write(f"ERROR: {LOCAL_DB} not found\n")
    sys.exit(1)


def sql_quote(v):
    """Escape a value for inline SQL. Returns 'NULL' for None."""
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return str(v)
    # single-quote escape SQL standard: '' inside ''
    return "'" + str(v).replace("'", "''") + "'"


def main():
    db = sqlite3.connect(LOCAL_DB)
    db.row_factory = sqlite3.Row

    out = sys.stdout.write
    out("-- Auto-generated migration from mypka.db → D1 larry-db\n")
    out("-- Generated by PKM/migrate-to-d1.py — re-run anytime, safe.\n\n")
    out("BEGIN TRANSACTION;\n\n")

    # ─── notes ─────────────────────────────────────────────────
    rows = db.execute(
        "SELECT slug, title, body, note_type, related_people, related_topics, "
        "source_journal_id, created_at FROM notes"
    ).fetchall()
    out(f"-- {len(rows)} notes\n")
    for r in rows:
        out(
            "INSERT OR IGNORE INTO notes "
            "(slug, title, body, note_type, related_people, related_topics, source_journal_id, created_at) "
            f"VALUES ({sql_quote(r['slug'])}, {sql_quote(r['title'])}, {sql_quote(r['body'])}, "
            f"{sql_quote(r['note_type'])}, {sql_quote(r['related_people'])}, "
            f"{sql_quote(r['related_topics'])}, {sql_quote(r['source_journal_id'])}, "
            f"{sql_quote(r['created_at'])});\n"
        )
    out("\n")

    # ─── journal ───────────────────────────────────────────────
    rows = db.execute(
        "SELECT entry_date, title, body, mood, source, related_people, "
        "related_topics, related_projects, created_at FROM journal"
    ).fetchall()
    out(f"-- {len(rows)} journal entries\n")
    for r in rows:
        out(
            "INSERT INTO journal "
            "(entry_date, title, body, mood, source, related_people, related_topics, related_projects, created_at) "
            f"VALUES ({sql_quote(r['entry_date'])}, {sql_quote(r['title'])}, "
            f"{sql_quote(r['body'])}, {sql_quote(r['mood'])}, {sql_quote(r['source'])}, "
            f"{sql_quote(r['related_people'])}, {sql_quote(r['related_topics'])}, "
            f"{sql_quote(r['related_projects'])}, {sql_quote(r['created_at'])});\n"
        )
    out("\n")

    # ─── people ────────────────────────────────────────────────
    rows = db.execute(
        "SELECT slug, full_name, known_as, role_context, notes, created_at, updated_at FROM people"
    ).fetchall()
    out(f"-- {len(rows)} people\n")
    for r in rows:
        out(
            "INSERT OR IGNORE INTO people "
            "(slug, full_name, known_as, role_context, notes, created_at, updated_at) "
            f"VALUES ({sql_quote(r['slug'])}, {sql_quote(r['full_name'])}, "
            f"{sql_quote(r['known_as'])}, {sql_quote(r['role_context'])}, "
            f"{sql_quote(r['notes'])}, {sql_quote(r['created_at'])}, "
            f"{sql_quote(r['updated_at'])});\n"
        )
    out("\n")

    out("COMMIT;\n")
    db.close()


if __name__ == "__main__":
    main()
