-- Auto-generated migration from mypka.db → D1 larry-db
-- Generated by PKM/migrate-to-d1.py — re-run anytime, safe.

BEGIN TRANSACTION;

-- 2 notes
INSERT OR IGNORE INTO notes (slug, title, body, note_type, related_people, related_topics, source_journal_id, created_at) VALUES ('coworking-berlin-rec', 'Coworking space rec for Sam', 'The one in Kreuzberg with day passes. Good wifi, quiet mornings.', 'followup', '["sam-porter"]', '[]', 1, '2026-05-05 14:33:47');
INSERT OR IGNORE INTO notes (slug, title, body, note_type, related_people, related_topics, source_journal_id, created_at) VALUES ('jamie-book-recs', 'Book recs for Jamie', 'Pick 3 from the longform shelf. Include one surprise.', 'followup', '["jamie-lee"]', '["longform-writing"]', 3, '2026-05-05 14:33:47');

-- 9 journal entries
INSERT INTO journal (entry_date, title, body, mood, source, related_people, related_topics, related_projects, created_at) VALUES ('2026-04-22', 'Morning Reset', 'Woke early. Walked 25 minutes before the first meeting. Thinking about the sabbatical plan.', 'steady', 'manual', '["sam-porter"]', '["longform-writing"]', '["sabbatical-plan-2026"]', '2026-05-05 14:33:47');
INSERT INTO journal (entry_date, title, body, mood, source, related_people, related_topics, related_projects, created_at) VALUES ('2026-04-23', 'Editing Day', 'Full day on the book draft intro. Cut 900 words.', 'focused', 'manual', '["dad-robert"]', '["longform-writing"]', '[]', '2026-05-05 14:33:47');
INSERT INTO journal (entry_date, title, body, mood, source, related_people, related_topics, related_projects, created_at) VALUES ('2026-04-24', 'Real Personal Day', 'Morning walk done. Tightened sabbatical budget. Coffee with Jamie. Writing block 600 words.', 'steady', 'manual', '["jamie-lee","sam-porter"]', '["longform-writing"]', '["sabbatical-plan-2026"]', '2026-05-05 14:33:47');
INSERT INTO journal (entry_date, title, body, mood, source, related_people, related_topics, related_projects, created_at) VALUES ('2026-05-07', 'Note-Taking: Die 5 Rs', 'Note-Taking Area:

Record the lecture as fully and as meaningfully as possible.

This format provides the perfect opportunity for following through with the 5 Rs of note-taking:

Record: During the lecture, record in the main column as many meaningful facts and ideas as you can.
Reduce: As soon after as possible, summarize these facts and ideas concisely in the Cue Column. Summarizing clarifies meanings and relationships, reinforces continuity, and strengthens memory.
Recite: Using only your jottings in the Cue Column, say over the facts and ideas of the lecture as fully as you can, not mechanically, but in your own words. Then, verify what you have said.
Reflect: Draw out opinions from your notes and use them as a starting point for your own reflections on the course and how it relates to your other courses. Reflection will help prevent ideas from being inert and soon forgotten.
Review: Spend 10 minutes every week in quick review of your notes, and you will retain most of what you have learned.', NULL, 'manual', NULL, '["note-taking", "lernen", "methoden", "cornell-notes"]', NULL, '2026-05-07 08:34:14');
INSERT INTO journal (entry_date, title, body, mood, source, related_people, related_topics, related_projects, created_at) VALUES ('2024-11-07', 'Marktanalysen: AI-Marktwert', 'Fundrise-Analyse zum Thema «How much will AI be worth?». Quelle: https://fundrise.cdn.prismic.io/fundrise/ZvroJ7VsGrYSwK01_HowmuchwillAIbeworth_-1-.pdf', NULL, 'manual', NULL, '["marktanalyse", "ai", "investitionen"]', NULL, '2026-05-07 09:03:04');
INSERT INTO journal (entry_date, title, body, mood, source, related_people, related_topics, related_projects, created_at) VALUES ('2024-11-08', 'Chartanalyse für Trading-Anfänger', 'TradingFreaks YouTube-Tutorial. Kerzenformationen: grün = Schluss > Eröffnung, rot = Schluss < Eröffnung. Trends: Aufwärts = höhere Hochs + höhere Tiefs. Indikatoren: RSI (>70 überkauft, <30 überverkauft), Fibonacci Retracement, Gleitender Durchschnitt. Strategie: EMA50 + RSI. Risikomanagement: max. 1-2% pro Trade. Psychologie: Angst, Gier, Übermut, Hoffnung als typische Fehlerquellen.', NULL, 'manual', NULL, '["chartanalyse", "trading", "technische-analyse", "rsi", "fibonacci"]', NULL, '2026-05-07 09:03:04');
INSERT INTO journal (entry_date, title, body, mood, source, related_people, related_topics, related_projects, created_at) VALUES ('2024-11-20', 'Geschichte der Philosophie', 'Thales von Milet gilt als erster Philosoph des Abendlands. Er ersetzt den Mythos durch den Logos. Vorsokratiker: Thales, Anaximander, Pythagoras, Heraklit, Parmenides, Demokrit. Klassik: Sokrates, Platon, Aristoteles. Epochen: Antike, Christentum/Mittelalter, Moderne (Rationalismus, Empirismus, Aufklärung, Dt. Idealismus), Post-Moderne.', NULL, 'manual', NULL, '["philosophie", "geschichte", "thales", "vorsokratiker", "antike"]', NULL, '2026-05-07 09:03:04');
INSERT INTO journal (entry_date, title, body, mood, source, related_people, related_topics, related_projects, created_at) VALUES ('2024-11-29', 'Religionen — Weltüberblick', 'Christentum: monotheistisch, ~2,3 Mrd. Anhänger, Dreifaltigkeit, Bibel, Konfessionen (Katholizismus, Protestantismus, Orthodoxie). Buddhismus: Siddhartha Gautama, Vier Edle Wahrheiten, Achtfacher Pfad, Traditionen Theravada/Mahayana/Vajrayana. Weitere Themen: griechische/römische Götter, europäische Dynastien, Weltreligionen-Karte, Alphabet-Evolution, chinesische Zeichen, Islam (notiert).', NULL, 'manual', NULL, '["religionen", "geschichte", "christentum", "buddhismus", "mythologie", "griechenland", "rom"]', NULL, '2026-05-07 09:03:04');
INSERT INTO journal (entry_date, title, body, mood, source, related_people, related_topics, related_projects, created_at) VALUES ('2024-12-03', 'Weight Loss: Dr. Paul Mason — Hormone statt Kalorien', 'Dr. Paul Mason widerlegt Kalorien-Modell. Insulin ist das Schlüsselhormon für Fettspeicherung. Hohe Kohlenhydrate -> hoher Insulinspiegel -> Fett. Empfehlungen: min. 2g Protein/kg, Samenöle meiden, Kohlenhydrate reduzieren. Lektine können Insulinrezeptoren aktivieren. CGM zur Glukose-Überwachung empfohlen. Taillenumfang statt Waage. Subklinische Hypothyreose häufig unterschätzt.', NULL, 'manual', NULL, '["gesundheit", "ernaehrung", "gewichtsabnahme", "insulin", "hormone", "low-carb"]', NULL, '2026-05-07 09:03:04');

-- 4 people
INSERT OR IGNORE INTO people (slug, full_name, known_as, role_context, notes, created_at, updated_at) VALUES ('sam-porter', 'Sam Porter', 'Sam', 'long-time friend, designer', 'Mulling Berlin move', '2026-05-05 14:33:47', '2026-05-05 14:33:47');
INSERT OR IGNORE INTO people (slug, full_name, known_as, role_context, notes, created_at, updated_at) VALUES ('dad-robert', 'Robert (Dad)', 'Dad', 'family', 'Doctor update 2026-04-23', '2026-05-05 14:33:47', '2026-05-05 14:33:47');
INSERT OR IGNORE INTO people (slug, full_name, known_as, role_context, notes, created_at, updated_at) VALUES ('jamie-lee', 'Jamie Lee', 'Jamie', 'new friend, reader', 'Asked for 3 book recs', '2026-05-05 14:33:47', '2026-05-05 14:33:47');
INSERT OR IGNORE INTO people (slug, full_name, known_as, role_context, notes, created_at, updated_at) VALUES ('markus-heiniger', 'Markus Heiniger', NULL, NULL, NULL, '2026-05-05 20:33:33', '2026-05-05 20:33:33');

COMMIT;
